In [ ]:
student={
    1:'first','name':'Dipson','age':20,'courses':['math','science']
}
print(student)
print(student['age'])

{1: 'first', 'name': 'Dipson', 'age': 20, 'courses': ['math', 'science']}
20


In [ ]:
students=dict(name='Dipson',age=30,city='london')
students

{'name': 'Dipson', 'age': 30, 'city': 'london'}

In [ ]:
students['job']='engineer'
print(students)

{'name': 'Dipson', 'age': 30, 'city': 'london', 'job': 'engineer'}


In [ ]:
del students['age']
print(students)

KeyError: 'age'

In [ ]:
for key,value in student.items():
    print(key,value)

1 first
name Dipson
age 20
courses ['math', 'science']


In [ ]:
for key in student:
    print(key)

1
name
age
courses


In [ ]:
for key,value in students.items():
    print(key,value)

name Dipson
city london
job engineer


In [ ]:
students={
    'student1':{
        'name':'Dipson',
        'age':20,
        'courses':['math','science']
    },
    'student2':{
        'name':'Dipson',
        'age':20,
        'courses':['math','science']
    }
}
print(students)

{'student1': {'name': 'Dipson', 'age': 20, 'courses': ['math', 'science']}, 'student2': {'name': 'Dipson', 'age': 20, 'courses': ['math', 'science']}}


In [ ]:
# students['student']['name'] # This line caused the error
students['student1']['name'] # Accessing the name of student1

'Dipson'

Numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
from array import array
a=array('f',[1,2,3,4])
a

array('f', [1.0, 2.0, 3.0, 4.0])

In [ ]:
a=np.ones(10)

In [ ]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=np.ones(10)

In [ ]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Change np.arrange(10) to np.arange(10)
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z=np.linspace(2,10,20) #useful for ploating
z

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [ ]:
a_list=[1,2,3,4,5,6,7,8,9]
z=np.array(a_list)


In [ ]:
type(z)

numpy.ndarray

In [ ]:
z=np.random.randint(1,51,size=50)
z

array([ 2, 43, 35, 46, 14, 35, 15, 34,  3, 38, 16,  2, 38,  9, 18,  3, 25,
       24, 20,  6, 32, 42, 45, 37, 43, 27, 25, 37, 21, 10, 29, 30, 10,  6,
       32, 34, 22, 44, 33, 33, 28, 47, 33, 37, 22, 10, 29, 44, 37, 46])

In [ ]:
z=np.sort(z)#kind='heapsort'

In [ ]:
z

array([ 2,  2,  3,  3,  6,  6,  9, 10, 10, 10, 14, 15, 16, 18, 20, 21, 22,
       22, 24, 25, 25, 27, 28, 29, 29, 30, 32, 32, 33, 33, 33, 34, 34, 35,
       35, 37, 37, 37, 37, 38, 38, 42, 43, 43, 44, 44, 45, 46, 46, 47])

In [ ]:
z[::-1]

array([47, 46, 46, 45, 44, 44, 43, 43, 42, 38, 38, 37, 37, 37, 37, 35, 35,
       34, 34, 33, 33, 33, 32, 32, 30, 29, 29, 28, 27, 25, 25, 24, 22, 22,
       21, 20, 18, 16, 15, 14, 10, 10, 10,  9,  6,  6,  3,  3,  2,  2])

In [ ]:
np.delete(a,1,0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])