**Basic Print**


In [ ]:
print("Hello World")
print('Hello World')
print('''Hello World''')

Hello World
Hello World
Hello World


In [ ]:
print('hello mf')

hello mf


In [ ]:
print("This MF rate is",100)

This MF rate is 100


In [ ]:
print("1+1=",5-3)

1+1= 2


In [ ]:
str="hay"
str[2]="r"

TypeError: 'str' object does not support item assignment

In [ ]:
str="her"

In [ ]:
str

'her'

Variable

In [ ]:
name="Dipson"
age=18
gpa=4.0
is_active=True
Present=None
Colors=['red','green','yellow','blue']
tuple=(1,2,3,4)
set={1,2,3,4,}
dict={'name':'Dipson','age':'18'}

In [ ]:
print(name)
print(type(name))

Dipson
<class 'str'>


In [ ]:
print(age)

18


In [ ]:
print(name)
print(type(name))
print(type(age))
print(Colors)
Colors[3]=1
print(tuple)
print(set)
print(dict["name"])

Dipson
<class 'str'>
<class 'int'>
['red', 'green', 'yellow', 'blue']
(1, 2, 3, 4)
{1, 2, 3, 4}
Dipson


In [ ]:
name='Dipson'

if name=='Dipson':
  print('Successfully login')
  if(True):
    print('Hi welcome back Dipson')
  else:
    print('Invalid User')

Successfully login
Hi welcome back Dipson


In [ ]:
age=14

if age<=18:
  print('you are unable to watch video')
elif age>=18 and age<54:
    print('you are able to watch video')
else:
   print('you guys are *****')


you are unable to watch video


In [ ]:
name="'Dipson'\n"
print(name*5)

'Dipson'
'Dipson'
'Dipson'
'Dipson'
'Dipson'



In [ ]:
a=9
b=6
a+=b
print(a)
a-=b
print(a)
a*=b
print(a)
a/=b
print(a)

15
9
54
9.0


In [ ]:
a=4
b=5
a,b=b,a
print(a,b)

5 4


In [ ]:
name[1:7]

name[::-1]

"\n'nospiD'"

Make a String Variable and check if its pallindron or not?

In [ ]:

str='racecar'
str[::-1]
if str==str[::-1]:
  print('palindrom')
else:
    print('not palindrom')

palindrom


In [ ]:
fruits = ["apple", "banana", "cherry"]
print(fruits[-1])


cherry


In [ ]:
"apple" in fruits


True

In [ ]:
"mango " in fruits

False

In [ ]:
fruits.pop()
print

In [ ]:
fruits.pop(1)

'banana'

In [ ]:
fruits.sort()
print(fruits)


['apple', 'cherry', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango']


In [ ]:
fruits.append("mango")
print(fruits)


['apple', 'cherry', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango']


In [ ]:
print(fruits.count('mango'))

11


In [ ]:
#nested list

In [ ]:
list1=[1,2,3,[4,5]]
list1[-1]
print(4 in list1)
print(4,5 in list1)
print(4 in list1[3])
l

False
4 False
True


In [ ]:
list2=[1,2,3],[4,5,6],[7,8,9]
print(list2[2][0])

7


In [ ]:
#for loop


In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
fruits = [fruits]
for fruit in fruits:
    print(fruit)

[[['apple', 'cherry', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango', 'mango']]]


In [ ]:
#while loop

In [ ]:
count = 0
while i<5:
  print(i)
  i +=1

4


list comprehension


In [ ]:
for x in range(2,7)
print(x)


In [ ]:
squares = [x**2 for x in range(1,5)]
print(squares)

[1, 4, 9, 16]


In [ ]:
'bus'.upper()


'BUS'

In [ ]:
'bus'.lower()


'bus'

In [ ]:
words = ['apple'] # Example: replace 'apple' with the desired fruit name string
uppercased_words = [word.upper() for word in words]
print(uppercased_words)

['APPLE']


In [ ]:
#set

In [ ]:
fruits = {'apple', 'banana', 'cherry'}
print(fruits)
#can't use indexing in set

{'banana', 'apple', 'cherry'}


In [ ]:
fruits = {'apple', 'banana', 'cherry'} # Re-initialize the set with elements
fruits.pop()
print(fruits)

{'apple', 'cherry'}


In [ ]:
#tupple unpacking

In [ ]:
fruits = ('apple', 'banana', 'cherry')
(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [ ]:
fruits=('apple','banana','cherry')
(green, yellow, red)=fruits
print(green)

apple


In [ ]:
#tuple has less time and space complexity than list
import time
import sys
L=list(range(100000))
T=tuple(range(100000))
start= time.time()
for i in L:
  i*10
print("List time= ",time.time()-start)
start= time.time()
for i in T:
  i*10
print('Tuple time= ',time.time()-start)
print('List size',sys.getsizeof(L))
print('Tuple size',sys.getsizeof(T))

List time=  0.011841773986816406
Tuple time=  0.00983738899230957
List size 800056
Tuple size 800040


DAY_4

In [ ]:
#creating dis.

In [ ]:
student={
    1:"first",
    "name":"shishir",
    "age":20,
    "courses":["math","science"]
}
print(student["age"])

20


In [ ]:
student = dict(name = "shishir",age=20,city="citty")
print(student)

{'name': 'shishir', 'age': 20, 'city': 'citty'}


In [ ]:
student["work"]="Study"
student['workplace']="office"
print(student)

{'name': 'shishir', 'age': 20, 'city': 'citty', 'work': 'Study', 'workplace': 'office'}


In [ ]:
del student['work']
print(student)

{'name': 'shishir', 'age': 20, 'city': 'citty', 'workplace': 'office'}


In [ ]:
del student['name']
print(student)

{'age': 20, 'city': 'citty', 'workplace': 'office'}


In [ ]:
student.values()
type(student.values())
if 'name' in student:
  print(student['name'])
  print(student.get('name'))


In [ ]:
for value in student.values():
  print(value)
  print(type(value))

20
<class 'int'>
citty
<class 'str'>
office
<class 'str'>


NESTED DICTIONARY

In [ ]:
student = {
    "student_1": {
        "name": "shishir",
        "age": 20,
        "courses": ["math", "science"]
    },
    "student_2": {
        "name": "bhattarai",
        "age": 20,
        "courses": ["engg", "computer"]
    }
}

In [ ]:
student["student_1"]['name']

'shishir'

In [ ]:
squares={x**2 for x in range(1,5)}
print(squares)

{16, 1, 4, 9}


In [ ]:
squares = {x: x**2 for x in range(1, 5)}
print(squares)

NUMPY

In [ ]:
!pip install numpy


In [ ]:
import numpy as np

a = np.ones(10,dtype=np.longdouble)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
z=np.zeros(5)

In [ ]:
np.arange(10,21 -2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
z=np.linspace(1,20,3,dtype=int)
print(z)

[ 1 10 20]


In [ ]:
np.linspace(20,10,2,dtype=int)

array([20, 10])

In [ ]:
s_list =[1,2,3,4,5,6,7,8,9]
s=np.array(s_list)
print(s)

[1 2 3 4 5 6 7 8 9]


In [ ]:
s=np.random.randint(1,10,size=(1,2,4))
print(s)

[[[8 4 4 4]
  [2 4 4 7]]]


In [ ]:
print(np.short(s),"ascending")

[[[8 4 4 4]
  [2 4 4 7]]] ascending


In [ ]:
s_list=list(range(10))
print(s_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
s[::-1]

array([[[8, 4, 4, 4],
        [2, 4, 4, 7]]])

In [ ]:
print(s)

[[[8 4 4 4]
  [2 4 4 7]]]


In [ ]:
s.shape

(1, 2, 4)

In [ ]:
a.size

16

In [ ]:
a=np.append(a,[2,1,3])
a=s
print(a)

[8 4 4 4 7]


In [ ]:
s=np.delete(s,2)
print(s)

[8 4 7]


[8 4 4 4 7]
